# Site settings
title: Binny V A
email: binnyva at gmail
description: > # this means to ignore newlines until "baseurl:"
  Just another Jekyll page. ;-)
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://binnyva.com" # the base hostname & protocol for your site
twitter_username: binnyva
github_username:  binnyva

# Build settings
markdown: kramdown
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

